runtime: go116
service: default
main: ./cmd/

instance_class: F1
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 1
  min_pending_latency: 100ms
  max_pending_latency: 300ms

env_variables:
  FIREBASE_CONFIG_FILE: 'firebase-adminsdk.json'

handlers:
  - url: /api
    static_files: static/index.html
    upload: static/index.html
  - url: /api/openapi.yaml
    static_files: api/openapi.yaml
    upload: api/openapi.yaml
  - url: /api/(.*)
    static_files: static/\1
    upload: static/(.*)
