version: '3'

networks:
  backend:

services:
  firebase:
    image: 'andreysenov/firebase-tools'
    volumes:
      - '.:/home/node'
    networks:
      - backend
    ports:
      - '4000:4000' # UI
      - '9099:9099' # Auth
      - '9100:9100' # Firestore
    command: ['firebase', 'emulators:start']

  app:
    depends_on:
      - firebase
    build:
      context: '.'
      dockerfile: './Dockerfile'
    networks:
      - backend
    ports:
      - '8080:8080'
    environment:
      #- GOOGLE_APPLICATION_CREDENTIALS=./firebase.key.json   # No private key for you :^)
      FIREBASE_CONFIG: '{"projectId": "serdok-pokemon-go"}'
      FIREBASE_AUTH_EMULATOR_HOST: localhost:9099
      FIRESTORE_EMULATOR_HOST: localhost:9100
