version: '3'

networks:
  backend:

services:
  app:
    build:
      context: '.'
      dockerfile: './Dockerfile'
    networks:
      - backend
    ports:
      - '8080:8080'

  firebase:
    image: 'andreysenov/firebase-tools'
    volumes:
      - '.:/home/node'
    networks:
      - backend
    ports:
      - '4000:4000' # UI
      - '9099:9099' # Auth
      - '8080:8080' # Firestore
    command: ['firebase', 'emulators:start']
